import type { ConfigValue } from '../../core/config.js';
import type { RmanConfig, ScopedVars } from '../../interfaces/rman-config.interface.js';
import type { CiService } from './services/ci.service.js';

/**
 * The `.rmanrc` keys that only mean something because the repository is a Node one.
 *
 * **One key, and it is here because no single command owns it**: `packageManager` is read by `ci`
 * *and* by the `npm` publish target, so neither can contribute it. Everything else this package
 * adds to `.rmanrc` is declared by whoever reads it - `clean.*` by `clean.command.ts` (through
 * `CommandContribution`), `publish.npm.*` by the target, below.
 *
 * **Two surfaces, and they are not alternatives:**
 *
 * - the `declare module 'rman'` block in [`../augmentation/rman.augmentation.ts`] merges this into
 *   `RmanConfigKeys`, so `repository.config.packageManager` stays typed wherever it is read with no
 *   cast. It lives there because one such block per package is the limit;
 * - `RmanNodeConfig` is the name a *config author* annotates with, which is what makes the import
 *   carrying that augmentation explicit instead of a side effect someone has to remember.
 */
export interface NodeConfigKeys {
  /**
   * Which package manager `ci`/`publish` shell out to, and whose version `info` reports under
   * `Binaries`. Root level only. Default `npm`.
   *
   * It used to be a core key, on the grounds that `info` read it - and that stopped being true the
   * moment `SystemInfo`'s npm half moved here: measured, **nothing in rman's core reads it at
   * all**, only the declaration was left behind. The value set was npm's tooling the whole time.
   */
  packageManager?: CiService.PackageManager;
}

export namespace RmanNodeConfig {
  /**
   * **`publish.npm.*`** - the `npm` publish target's own block, contributed through the
   * `PublishTargetConfigs` slot rman's `publish` command exports for any target.
   *
   * Named after the target, the way `publish.docker.*` already was. It used to be `publish.directory`
   * - a bare key sitting directly beside `target`, `skip` and `docker`, so the one block that was
   * *not* a target's read as though it belonged to publishing in general. `target` and `skip` are
   * genuinely `publish`'s own; `directory` never was.
   */
  export interface NpmPublishOptions extends NpmPublishOptionsKeys, ScopedVars {}

  export interface NpmPublishOptionsKeys {
    /** Where this package's publishable output lives, relative to its own directory (e.g.
     *  `"build"`). Per-package cascaded, so a root `"[*]"` block can say it once for the whole
     *  repository instead of repeating `publishConfig.directory` in every `package.json` - which
     *  still wins when a package declares it, being the more specific statement.
     *
     *  Publishing from such a directory means the manifest there is **generated by `publish`**,
     *  from the package's own - see `PublishService`. There is nothing to configure about it. */
    directory?: ConfigValue<string>;
  }
}

/**
 * `.rmanrc` for a repository using this plugin: rman's own keys plus the ones above.
 *
 * ```js
 * // .rmanrc.mjs
 * import { defineConfig } from 'rman';
 *
 * export default defineConfig({
 *   plugins: ['node'],
 *   '[*]': { clean: { include: 'build' }, publish: { npm: { directory: 'build' } } },
 * });
 * ```
 *
 * `.mjs`, not `.ts`: rman loads `.rmanrc.cjs`/`.mjs`/`.js` and no TypeScript form, so the type
 * reaches a config file through the editor rather than through a compiler. The JSON and YAML forms
 * carry no type at all - since the JSON Schema was removed, they are unchecked.
 */
export interface RmanNodeConfig extends RmanConfig {}

/**
 * Identity helper for authoring a `.rmanrc.mjs`/`.cjs`/`.js` config with this plugin's keys checked
 * - rman's own `defineConfig` with a narrower parameter, nothing more. Returns `config` unchanged.
 */
export function defineConfig(config: RmanNodeConfig): RmanNodeConfig {
  return config;
}
