language: node_js
node_js:
  - "14"
  - "16"
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.npm"
    - node_modules
install:
  - "npm install"
script:
- "npm run-script travis-cover"
after_script:
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"
