import type { PublishFilesKeys } from '../../../core/interfaces/publish-target.js';
import type { ConfigValue, RmanConfig, ScopedVars } from '../../../interfaces/rman-config.interface.js';
import type { CiService } from './services/ci.service.js';

/**
 * The `.rmanrc` keys that only mean something because the repository is a Node one, merged into
 * `RmanConfigKeys` by `rmanrc.augmentation.ts`. Everything else this built-in adds is declared by
 * whoever reads it - `clean.*` by `clean.command.ts`, `publish.npm.*` by the target, below.
 */
/* **Empty since `packageManager` became a map keyed by platform** - it is the core's key now, and
 * Node contributes its entry through `NodePackageManagers`. Kept as the place a Node-only key would
 * go, and because `RmanNodeConfig` and the package's exports name it. */

export interface NodeConfigKeys {}

/**
 * Node's entry in `.rmanrc "packageManager"`: which package manager `ci` installs with, `publish`
 * publishes with and `info` reports - `packageManager: { node: pnpm }`. Default `npm`.
 */
export interface NodePackageManagers {
  node?: CiService.PackageManager;
}

export namespace RmanNodeConfig {
  /**
   * **`publish.npm.*`** - the `npm` publish target's own block, contributed through the
   * `PublishTargetConfigs` slot rman's `publish` command exports for any target.
   *
   * Named after the target, the way `publish.docker.*` already was. It used to be `publish.directory`
   * - a bare key sitting directly beside `target`, `skip` and `docker`, so the one block that was
   * *not* a target's read as though it belonged to publishing in general. `target` and `skip` are
   * genuinely `publish`'s own; `directory` never was.
   */
  export interface NpmPublishOptions extends NpmPublishOptionsKeys, ScopedVars {}

  export interface NpmPublishOptionsKeys extends PublishFilesKeys {
    /** Where this package's publishable output lives, relative to its own directory (e.g.
     *  `"build"`). Per-package cascaded, so a root `"[*]"` block can say it once for the whole
     *  repository instead of repeating `publishConfig.directory` in every `package.json` - which
     *  still wins when a package declares it, being the more specific statement.
     *
     *  Publishing from such a directory means the manifest there is **generated by `publish`**,
     *  from the package's own - see `PublishService`. There is nothing to configure about it. */
    directory?: ConfigValue<string>;
    /**
     * Publish into npm's **staging queue** (`npm stage publish`) instead of straight to the
     * registry: the version is held pending until a maintainer approves it with `npm stage approve`,
     * which is the step that carries the 2FA challenge.
     *
     * Per package like every other key here, so a repository can stage the one package that matters
     * and publish the rest directly.
     *
     * Requires npm >= 11.15.0 and Node >= 22.14.0 on whatever runs the publish. rman does not check
     * either: the version that matters is the runner's, not the one resolving the config, and npm's
     * own "Unknown command: stage" is a better message than a guess made somewhere else.
     */
    staged?: ConfigValue<boolean>;
    /**
     * The prerelease identifiers that are **not previews** for this package - a version on one of
     * them publishes to `latest` like a release, instead of under a dist-tag of its own.
     *
     * For a package whose every release is a prerelease by design: `["rev"]` publishes
     * `4.13.3-rev.9` to `latest`, while a `4.14.0-beta.0` of the same package keeps its own `beta`
     * tag. Pairs with `.rmanrc "version.preid"`.
     *
     * @example ["rev"]
     */
    latestPrereleases?: ConfigValue<string[]>;
  }
}

/**
 * `.rmanrc` for a repository using this plugin: rman's own keys plus the ones above.
 *
 * ```js
 * // .rmanrc.mjs
 * import { defineConfig } from 'rman';
 *
 * export default defineConfig({
 *   plugins: ['node'],
 *   '[*]': { clean: { include: 'build' }, publish: { npm: { directory: 'build' } } },
 * });
 * ```
 *
 * `.mjs`, not `.ts`: rman loads `.rmanrc.cjs`/`.mjs`/`.js` and no TypeScript form, so the type
 * reaches a config file through the editor rather than through a compiler. The JSON and YAML forms
 * carry no type at all - since the JSON Schema was removed, they are unchecked.
 */
export interface RmanNodeConfig extends RmanConfig {}

/**
 * Identity helper for authoring a `.rmanrc.mjs`/`.cjs`/`.js` config with this plugin's keys checked
 * - rman's own `defineConfig` with a narrower parameter, nothing more. Returns `config` unchanged.
 */
export function defineConfig(config: RmanNodeConfig): RmanNodeConfig {
  return config;
}
