import type { RmanConfig, ScopedVars, WithAppend } from 'rman';
import type { CiService } from '../services/ci.service.js';

/**
 * The `.rmanrc` keys that only mean something because the repository is a Node one.
 *
 * Declared here rather than in rman's core for the reason the commands themselves are: `clean`
 * describes TypeScript's output, and `publish.directory` a `package.json` generated at publish
 * time. A Cargo or Go repository has neither, and a core interface offering them was a core
 * interface claiming to know npm.
 *
 * **Two surfaces, and they are not alternatives:**
 *
 * - the `declare module 'rman'` block in [`../augmentation/rman.augmentation.ts`] merges these into
 *   `RmanConfigKeys`, so `pkg.config.clean` stays typed wherever it is read - `CleanService`
 *   included - with no casts. It lives there because one such block per package is the limit;
 * - `RmanNodeConfig` is the name a *config author* annotates with, which is what makes the import
 *   carrying that augmentation explicit instead of a side effect someone has to remember.
 */
export interface NodeConfigKeys {
  /**
   * Which package manager `ci`/`publish` shell out to, and whose version `info` reports under
   * `Binaries`. Root level only. Default `npm`.
   *
   * It used to be a core key, on the grounds that `info` read it - and that stopped being true the
   * moment `SystemInfo`'s npm half moved here: measured, **nothing in rman's core reads it at
   * all**, only the declaration was left behind. The value set was npm's tooling the whole time.
   */
  packageManager?: CiService.PackageManager;
  /** Extra files and directories `clean` removes, beyond TypeScript's own output - globs relative
   *  to each package's own directory. Per-package cascaded; a package declaring its own `clean`
   *  block replaces the root's entirely for itself, rather than combining with it. */
  clean?: RmanNodeConfig.CleanOptions;
}

export namespace RmanNodeConfig {
  export interface CleanOptions extends CleanOptionsKeys, WithAppend<CleanOptionsKeys>, ScopedVars {}

  export interface CleanOptionsKeys {
    include?: string | string[];
    exclude?: string | string[];
    /** Excludes this package from `clean` entirely. */
    skip?: boolean;
  }

  /** Added to the core's `publish` block - the npm-only half of it. `target`, `skip` and `docker`
   *  stay in the core: the first two are read by `list` and by every target's own plan, and Docker
   *  publishing is not a Node concern at all. */
  export interface PublishOptions extends ScopedVars {
    /** Where this package's publishable output lives, relative to its own directory (e.g.
     *  `"build"`). Per-package cascaded, so a root `"[*]"` block can say it once for the whole
     *  repository instead of repeating `publishConfig.directory` in every `package.json` - which
     *  still wins when a package declares it, being the more specific statement.
     *
     *  Publishing from such a directory means the manifest there is **generated by `publish`**,
     *  from the package's own - see `PublishService`. There is nothing to configure about it. */
    directory?: string;
  }
}

/**
 * `.rmanrc` for a repository using this plugin: rman's own keys plus the ones above.
 *
 * ```js
 * // .rmanrc.mjs
 * import { defineConfig } from 'rman-node';
 *
 * export default defineConfig({
 *   plugins: ['rman-node'],
 *   '[ws:*]': { clean: { include: 'build' }, publish: { directory: 'build' } },
 * });
 * ```
 *
 * `.mjs`, not `.ts`: rman loads `.rmanrc.cjs`/`.mjs`/`.js` and no TypeScript form, so the type
 * reaches a config file through the editor rather than through a compiler. The JSON and YAML forms
 * carry no type at all - since the JSON Schema was removed, they are unchecked.
 */
export interface RmanNodeConfig extends RmanConfig {}

/**
 * Identity helper for authoring a `.rmanrc.mjs`/`.cjs`/`.js` config with this plugin's keys checked
 * - rman's own `defineConfig` with a narrower parameter, nothing more. Returns `config` unchanged.
 */
export function defineConfig(config: RmanNodeConfig): RmanNodeConfig {
  return config;
}
