import type { RmanPlugin } from '../core/plugin.js';

/**
 * Adds a `+key` alongside every key of `T`, which **appends** to whatever that key already resolved
 * to instead of replacing it - see `mergeConfig`.
 *
 * Generated by key remapping rather than written out, so a key added to the interface gets its
 * append form automatically and the two can never drift apart.
 */
export type WithAppend<T> = { [K in keyof T as `+${K & string}`]?: T[K] };

/**
 * The shape of `.rmanrc`/`.rmanrc.yml`/`.rmanrc.cjs`/`.mjs`/`.js` (and `package.json`'s own
 * `"rman"` key) - see docs/rman.md#configuration-rmanrc-rmanrcyml for the full reference. Every
 * field is optional and cascades from the repository root down to each package's own directory.
 * Purely a typing aid (used by `defineConfig` below, and importable on its own for a `.rmanrc.ts`/
 * `.mts` authored config, or a plain `: RmanConfig` annotation) - never read by rman itself, which
 * only ever sees the plain JS object a JS config file exports.
 */
export interface RmanConfig extends RmanConfigKeys, WithAppend<RmanConfigKeys> {
  /**
   * Configs to inherit from, merged **underneath** this one - a shared package
   * (`"@panates/rman-monorepo"`), a relative path, or an array applied in declaration order.
   *
   * A bare name resolves through *this* file's own `node_modules`, so a subpath works too
   * (`"@panates/rman-monorepo/strict"`). The target may be YAML, JSON, or a module exporting a
   * config via `defineConfig`, and may itself `extends` another.
   *
   * Top level only: a `"[selector]"` block naming one is an error rather than a no-op, since
   * inheritance is a statement about this config and not about the packages a selector names.
   */
  extends?: string | string[];
}

/** Every setting a config may carry, without the `+key` append forms or `extends` - the shape
 *  `RmanConfig` is built from, kept separate only so `WithAppend` has something to map over. */
export interface RmanConfigKeys {
  /**
   * **A plugin adds its own keys here, by declaration merging** - `@rman/node` contributes
   * `clean` and `publish.directory` from its own
   * `interfaces/rman-config.interface.ts`, so `pkg.config.clean` stays typed wherever it is read
   * without the core having to know npm has a `node_modules` or that TypeScript has build output.
   * `WithAppend` is a mapped type evaluated at use, so an augmented key gets its `+key` form too.
   *
   * A config author annotates with the plugin's own name for the union - `RmanNodeConfig` - which
   * is what makes the import that carries the augmentation explicit rather than incidental.
   */
  /**
   * Plugins to load, in declaration order - a *package* contributing commands, where `.rman/*.mjs`
   * contributes one repository's own.
   *
   * Each entry is **either a package name (or path) to import, or a plugin object itself**:
   *
   * ```yaml
   * # .rmanrc.yml - imported by name, resolved through the repository's own node_modules
   * plugins: ['@rman/node']
   * ```
   *
   * ```js
   * // .rmanrc.mjs - or handed over directly, which a JS config can do and a YAML one cannot
   * import { defineConfig, definePlugin } from 'rman';
   * export default defineConfig({ plugins: [definePlugin({ name: 'mine', commands: [...] })] });
   * ```
   *
   * The object form is what lets a **plugin package export a config** rather than a single plugin:
   * `@rman/node`'s entry point is `export default defineConfig({ plugins: [ ... ] })`, so it is an
   * `.rmanrc` like any other and is free to grow a second plugin without changing its shape. When an
   * imported module exports a config this way, **only its `plugins` are read** - a config's other
   * keys reach a repository through `extends`, which is the key that means "merge this underneath
   * mine".
   *
   * This is how everything that only means something in a Node repository lives outside rman's
   * core. A plugin that cannot be loaded is an error, not a skip: silently losing `rman publish` is
   * worse than not starting.
   *
   * Root level only - which commands exist is a property of the repository, not of a package.
   */
  plugins?: string | RmanPlugin | (string | RmanPlugin)[];

  /**
   * Values for `${{ vars.* }}` to read - a name for something the config would otherwise repeat:
   *
   * ```yaml
   * vars:
   *   outDir: build
   *   image: 'panates/${{ pkg.basename }}'
   * "[*]":
   *   publish:
   *     directory: '${{ vars.outDir }}'
   * ```
   *
   * Any shape, and the values may themselves be expressions - they are evaluated for the package
   * reading them, so one `vars.image` gives each package its own.
   *
   * **The one unmarked key that reaches every package**, rather than only the package of the
   * directory declaring it. A package (or a `"[selector]"` block) overrides it **per key**, so
   * redefining one var keeps the rest.
   */
  vars?: Record<string, unknown>;
  logLevel?: 'silent' | 'error' | 'info' | 'verbose';
  allowBranch?: string | string[];
  ignoreBranch?: string | string[];
  /**
   * Leave this package alone: **every command that acts on packages skips it** - `run`/`build`/
   * `test`, `exec`, `clean`, `publish`, `version`, `changelog`. Per-package cascaded, so a root
   * `"[selector]"` block can say it for several at once.
   *
   * One standing statement rather than a `skip` invented per command, which is what it was: three
   * separate keys carried it and none of them meant quite the same thing. The finer-grained ones
   * remain for when only one command should stop - `run.<script>.skip` for a single script,
   * `publish.skip` for "never distributed, by any target" (which `changelog` reuses on purpose).
   *
   * **The commands that *report* deliberately ignore it** - `list` still shows the package, because
   * it is still in the repository and an inventory hiding part of one is answering a different
   * question. `changed` follows `version`, since its whole job is to say what `version` would do.
   */
  skip?: boolean;
  group?: boolean | string;
  version?: RmanConfig.VersionOptions;
  changelog?: RmanConfig.ChangelogOptions;
  publish?: RmanConfig.PublishOptions;
  githubRelease?: RmanConfig.GithubReleaseOptions;
  /** Keyed by npm script name (e.g. `"build"`, `"lint"`, `"test"`). A bare string (or array of
   *  them) is shorthand for `{ exec: ... }` - `test: "mocha"` and `test: { exec: "mocha" }` mean
   *  exactly the same thing. */
  run?: Record<string, string | string[] | RmanConfig.RunScriptOptions>;
  /**
   * In-repo packages this one depends on **beyond what its own manifest declares** - purely for
   * rman's own dependency graph (topo-sort, `--deps`/`--dependents`, `run`'s scheduling, the version
   * cascade). Declared from the root via a selector (`"[pkg-a]": { dependencies: [...] }`) or in the
   * package's own `.rmanrc`.
   *
   * Each entry is a package **name, or a repository-relative directory** - tried in that order. The
   * path form is not a convenience: a name identifies a package only where the ecosystem guarantees
   * uniqueness, which npm does and others do not, while a directory is unique by construction. It is
   * the same reason `Workspace.Layout` carries paths and `Package.dependencies` holds references
   * rather than names.
   *
   * **A list, and only a list.** It used to accept a `Record<string, string>` too, documented as "an
   * explicit name -> range map" - and the ranges went nowhere: the one reader took `Object.keys` and
   * dropped the values. Nor could they ever mean anything here, since the cascade works from groups
   * and severities, and `ManifestProvider.updateDependencyVersions` rewrites ranges in the
   * *manifest* - a range declared only in `.rmanrc` has no file to be written to. What this key
   * states is an **edge**, and an edge needs two ends and nothing else.
   *
   * **Core, and it has to be**: it is layered on top of whatever `ManifestProvider.dependencies`
   * read, and it is the *only* way a repository with no provider at all has a graph - a repo whose
   * manifests rman cannot read can still state its edges by hand. Moving it to an ecosystem plugin
   * would take that away from exactly the repositories that need it.
   */
  dependencies?: string[];
  /**
   * Config for **other** packages, keyed by a `"[selector]"` naming them - `"[*]"` for every
   * package in the repository, `"[*-dialect]"` for a glob over package names, `"[pkg-a]"` for one.
   * Everything else in this object configures the package of the directory declaring it, so this
   * is the only way a `.rmanrc` speaks about anything but its own package - most usefully the
   * repository root's, which otherwise configures the root package alone.
   *
   * ```yaml
   * # the repository root's own .rmanrc.yml
   * run:
   *   build:
   *     before: node support/generate.cjs   # a repo-wide bookend, run once at the root
   * "[*]":
   *   run:
   *     build:
   *       after: node ../../support/postbuild.cjs   # run in each package's own directory
   * ```
   *
   * In YAML the quotes are **required**: a bare `[*]` parses as a flow sequence, and `*` as an
   * alias indicator. Precedence, lowest first: `"[*]"`, then other selectors in declaration order,
   * then the package's own unmarked config.
   *
   * Recursive, mirroring the schema's own `"$ref": "#"`: whatever a `.rmanrc` may say about its own
   * package it may say here about the ones it names - nested selectors included. Typed as
   * `RmanConfig` rather than `unknown` so the contents are actually checked; `unknown` let any
   * shape through, which is the opposite of the point.
   */
  [selector: `[${string}]`]: RmanConfig;
}

export namespace RmanConfig {
  /**
   * One `version.stamp` entry: a path, or a path plus the identifier that holds the version.
   *
   * The object form exists because the identifier was unnameable - only the exact lowercase word
   * `version` was ever matched, so a Go `const Version`, a Python `__version__` and a plain
   * `appVersion` were all silently skipped. What the identifier *means* is the ecosystem's
   * (`ManifestProvider.stampVersion`); which file holds one is the repository's, which is why it is
   * here.
   */
  export type VersionStampEntry = string | { file: string; constant?: string };

  export interface VersionOptions extends VersionOptionsKeys, WithAppend<VersionOptionsKeys> {}

  export interface VersionOptionsKeys {
    commitMessage?: string;
    /** Default for `version --changelog` when the CLI flag isn't given - a standing "always fold
     *  the changelog into the version-bump commit" policy, rather than something that behaves
     *  differently on the one run someone forgets to pass `--changelog`. An explicit `--changelog`/
     *  `--no-changelog` on the command line still wins either way. Root-level only. Default `false`. */
    changelog?: boolean;
    /** Tag naming the repository's own release, as opposed to the per-package/group tags
     *  `changelog.tagPattern` names - only created when the root is on a calendar version (a repo
     *  with more than one version line). Root-level only. Default `"release-*"`. Must **not** match
     *  any package's own `changelog.tagPattern`, or that package's changelog boundary will resolve
     *  to the repository release instead of its own last release. */
    releaseTagPattern?: string;
    /** Keep this package's Dockerfile `org.opencontainers.image.version` label in step with the
     *  version being written. Per-package cascaded. Default `true` - the label's value is, by
     *  specification, the version of the packaged software, so there is only ever one correct
     *  value for it, and `version` is what knows it. Only ever *rewrites* a label the Dockerfile
     *  already declares (never inserts one), and reads the same path `publish --target docker`
     *  builds from (`publish.docker.dockerfile`), so a package without one is a no-op. */
    stampDockerfile?: boolean;
    /** Files whose hard-coded version is rewritten to the version being written, in the same
     *  commit as the bump - paths relative to the package's own directory (e.g.
     *  `["src/constants.ts"]`). Per-package cascaded; a listed file a package doesn't have is a
     *  silent no-op, so one `"[*]"` declaration covers a repo where only some packages carry one.
     *
     *  Stamping the source, not the build output: a build-time rewrite leaves the checked-in file
     *  claiming a placeholder, so anything running from source reports that placeholder, git never
     *  records the released version, and the rewrite has to be redone on every build. */
    stamp?: VersionStampEntry | VersionStampEntry[];
    /** Command(s) run at the version write itself, when the package does not declare a hook for
     *  that slot of its own (`version` in a Node repository's `package.json#scripts`, whatever a
     *  plugin's step source answers elsewhere - the package's own declaration wins, as in `run`).
     *  An array runs them in sequence. `${{ pkg.targetVersion }}` is bound here and in the two
     *  below, and nowhere else. */
    exec?: string | string[];
    /** Same, before the write (`preversion` in a Node repository). */
    before?: string | string[];
    /** Same, after it (`postversion` in a Node repository). */
    after?: string | string[];
  }

  export interface ChangelogOptions extends ChangelogOptionsKeys, WithAppend<ChangelogOptionsKeys> {}

  export interface ChangelogOptionsKeys {
    ignoreTypes?: string[];
    template?: string;
    filePath?: string;
    tagPattern?: string;
  }

  export interface RunScriptOptions extends RunScriptOptionsKeys, WithAppend<RunScriptOptionsKeys> {}

  export interface RunScriptOptionsKeys {
    concurrency?: number;
    topo?: boolean;
    bail?: boolean;
    progress?: boolean;
    logLevel?: 'silent' | 'error' | 'info' | 'verbose';
    changedSince?: string;
    skip?: boolean;
    if?: string;
    /** Command(s) to run as this script itself, when the package's `package.json` doesn't define
     *  it. An array runs them in sequence. */
    exec?: string | string[];
    /** Same, for this script's `pre<script>` hook. */
    before?: string | string[];
    /** Same, for its `post<script>` hook. */
    after?: string | string[];
    override?: boolean;
  }

  export interface PublishOptions extends PublishOptionsKeys, WithAppend<PublishOptionsKeys> {}

  export interface PublishOptionsKeys {
    /** Which **registry** `publish` ships this package to - default `['npm']` (every existing repo
     *  keeps working unchanged). A package that only ever wants Docker images (typically also
     *  `"private": true`, since it's not meant for npm at all) sets `['docker']`; both works too.
     *  Each target answers "is this version already out there?" against its own registry, so a
     *  package is never left without one: npm via `npm view`, docker via `docker manifest inspect`.
     *
     *  Note this is strictly about *package distribution*. The repository's GitHub Release is not
     *  a target here - it isn't a place a package ships to, it's the repository's own record that
     *  a release happened, and it is never opted into: see `githubRelease` and the
     *  `github-release` command. */
    target?: PublishTarget | PublishTarget[];
    docker?: DockerPublishOptions;
    /** Excludes this package from `publish` entirely (every target), regardless of
     *  `target`/`"private"` - a single, explicit "never published" statement, e.g. for a package
     *  released through some separate, unrelated process. `changelog` also skips it by default
     *  (see its own `--include-skipped`) - there's little point changelogging something that's
     *  never actually released. Independent of `version`, which never consults this at all - a
     *  package can still be meaningfully versioned without ever being published. */
    skip?: boolean;
  }

  export type PublishTarget = 'npm' | 'docker';

  /** Required once `"docker"` is one of this package's `publish.target`s - `publish --target
   *  docker` errors clearly on a package that opts in here but leaves this out. */
  export interface DockerPublishOptions extends DockerPublishOptionsKeys, WithAppend<DockerPublishOptionsKeys> {}

  export interface DockerPublishOptionsKeys {
    /** DockerHub image name/repository - bare (e.g. `"my-app"`) to be prefixed with
     *  `--docker-namespace`/`DOCKERHUB_NAMESPACE`, or already-namespaced (contains a `/`) to use
     *  verbatim. */
    image: string;
    /** Relative to the package's own directory. Default `"Dockerfile"`. */
    dockerfile?: string;
    /** Default `["linux/amd64"]`. */
    platforms?: string[];
    /** Build `cwd` override, relative to the repository root - only needed when the Dockerfile's
     *  own `COPY`/`ADD` paths expect something other than the package's own directory (rare). */
    cwd?: string;
    /** Named `docker buildx build --build-context <name>=<path>` entries, keyed by name - each
     *  path is relative to the package's own directory (or absolute). */
    buildContexts?: Record<string, string>;
    /** `docker buildx build --build-arg <name>=<value>` entries - a value of exactly `"$NAME"`
     *  expands to `process.env.NAME` at build time (e.g. to pass a CI secret through). */
    buildArgs?: Record<string, string>;
    /** A file (relative to the package's own directory) whose contents become the DockerHub repo's
     *  full description, if present. Default `"DOCKER_README.md"`. */
    readme?: string;
  }

  /** Entirely optional - `github-release` needs no configuration at all, since every required fact
   *  (which tag, which repository, what the notes say) already has a sensible source. Nothing here
   *  decides *whether* a release is cut: a release records that the repository shipped, so it is
   *  always cut, and these are only details about how. */
  export interface GithubReleaseOptions extends GithubReleaseOptionsKeys, WithAppend<GithubReleaseOptionsKeys> {}

  export interface GithubReleaseOptionsKeys {
    /** Files to attach to the release, as glob patterns relative to the package's own directory
     *  (e.g. `["dist/*.tar.gz"]`). Read from **every** package, since one release covers the whole
     *  source tree. A release with no assets at all is still perfectly valid - it records that the
     *  version shipped, which is all a deploy-elsewhere package needs. */
    assets?: string[];
    /** `owner/repo`. Default: parsed from the `origin` remote's URL. Root-level only. */
    repository?: string;
    /** Create the release as an unpublished draft. Default `false`. Root-level only. */
    draft?: boolean;
    /** Default: whether the version being released is itself a prerelease by the root's own version
     *  scheme (`1.3.0-beta.0` under semver) - see `VersionScheme.isPrerelease`. Root-level only. */
    prerelease?: boolean;
  }
}
